Project/depression/depression/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('myapp/', include(('myapp.urls'),namespace = 'myapp')),
    path('admin/', admin.site.urls),
    
]

Project/depression/myapp/urls.py
from django.urls import path
#from django.urls import reverse
#from django.urls import redirect

from . import views

app_name = 'myapp'
urlpatterns = [
    path('', views.index,name='index'),
    path('home', views.home,name='home'),
    path('myapp/prediction', views.prediction,name='prediction'),
    path('myapp/results', views.results,name='results')
]  
#reverse('myapp.view.prediction')
#redirect('myapp.view.prediction')

Project/depression/myapp/models.py
from django.db import models

# Create your models here.

Project/depression/myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import joblib
import numpy as np
import pandas as pd

# Create your views here.
def index(request):
    return render(request,'index.html')

def home(request):
        return render(request,'home.html')

def prediction(request):
    
    if request.method == 'POST':
        Age = request.POST['Age']
        Gender = request.POST['Gender']
        family_history = request.POST['family_history']
        work_interfere = request.POST['work_interfere']
        benefits = request.POST['benefits']
        care_options = request.POST['care_options']
        wellness_program = request.POST['wellness_program']
        seek_help =request.POST['seek_help']
        anonymity = request.POST['anonymity']
        leave = request.POST['leave']
        mental_health_consequence = request.POST['mental_health_consequence']
        coworkers = request.POST['coworkers']
        mental_health_interview = request.POST['mental_health_interview']
        mental_vs_physical = request.POST['mental_vs_physical']
        obs_consequence = request.POST['obs_consequence']
        down = int(request.POST['down'])
        best = int(request.POST['best'])
        cry = int(request.POST['cry'])
        sleep = int(request.POST['sleep'])
        eat = int(request.POST['eat'])
        look = int(request.POST['look'])
        weight = int(request.POST['weight'])
        heart = int(request.POST['heart'])
        constipation = int(request.POST['constipation'])
        tired = int(request.POST['tired'])
        clear = int(request.POST['clear'])
        easy = int(request.POST['easy'])
        still = int(request.POST['still'])
        future = int(request.POST['future'])
        irritable = int(request.POST['irritable'])
        decision = int(request.POST['decision'])
        need = int(request.POST['need'])
        full = int(request.POST['full'])
        better = int(request.POST['better'])
        things = int(request.POST['things']) 

        data = [Age,Gender,family_history,work_interfere,benefits,care_options,
                wellness_program,seek_help,anonymity,leave,mental_health_consequence,coworkers,
                mental_health_interview,mental_vs_physical,obs_consequence]
        cols= ['Age', 'Gender', 'family_history', 'work_interfere', 'benefits',
       'care_options', 'wellness_program', 'seek_help', 'anonymity', 'leave',
       'mental_health_consequence', 'coworkers', 'mental_health_interview',
       'mental_vs_physical', 'obs_consequence']
        
        vars = [down,best,cry,sleep,eat,look,weight,heart,constipation,tired,clear,easy,still,
        future,irritable,decision,need,full,better,things]
        
        global index
        index = str((sum(vars) * 100)/80)

        df = pd.DataFrame([data],columns= cols)
        model = joblib.load('myapp/rfc.sav')        
        arr = np.array(data)
        classification = model.predict(df)

        global result
        result = str(classification[0])
        print(result)
        print(index)
        
        

        return JsonResponse({'result':result,'index':index})
        
        # r={'age':Age,'gender':Gender,
        # 'family_history':family_history,'work_interfere':work_interfere,'benefits':benefits,
        # 'care_options':care_options,'wellness_program':wellness_program,'seek_help':seek_help,
        # 'anonymity':anonymity,'leave':leave,'mental_health_consequence':mental_health_consequence,
        # 'coworkers':coworkers,'mental_health_interview':mental_health_interview,
        # 'mental_vs_physical':mental_vs_physical,'obs_consequence':obs_consequence},safe = False)


def results(request):  
       display = {'result':result,
        'index':index
        }
       return render(request,'results.html',display)



    

Project/depression/templates/base.html
{% load static %}
<!DOCTYPE html>
<head>
  <title>Mental health</title>

  <link rel="stylesheet"  href="{% static  'app/css/main.css'  %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
</head>
<body>
  <br>
  <div>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">PendaCare</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            
          </div>
        </nav>
  </div>
  <br>
  <div class = 'text-center'>
      <h2>Help US Get Your Good Mood Back</h2>
  </div>
  <br>
  <div class = 'text-center'>
      <p>Please fill out this short questionnaire to provide some general and anonymous background of your work place and how you've been feeling off late. 
          PendaCare values your mental health as it is a major challenge and if not taken seriously it can affect your daily activities.  .
           </p>
  </div>
  {% block content %}
  {% endblock%}

  <script src="{% static 'app/js/main.js' %}"></script>
</body>
<html>

Project/depression/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        
        <title>Mental Health</title>
        
        
        <link href="{%static 'project/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger">PendaCare</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container h-100">
                <div class="row h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-10 align-self-end">
                        <h1 class="text-uppercase text-white font-weight-bold">PendaCare Mental Health System</h1>
                        <hr class="divider my-4" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 font-weight-light mb-5">PendaCare is a self diagnostic tool meant for techies who might be feeling depressed at their work places.
                            You interact with a model that tells whether you need treatment or not then later classifies your level of depression and advises you further. </p>
                        <a class="btn btn-primary btn-xl" href='{%url  "myapp:home" %}'>Get Started</a>
                    </div>
                </div>
            </div>
        </header>
       
        
        <!-- Bootstrap core JS-->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'project/js/scripts.js' %}"></script>
    </body>
</html>